---
install: true
env:
- PROFILE=pedantic
- PROFILE=unittesting
- PROFILE=integrationTesting FIXTURES="-Dns-fixtures=SEGMENT_MK" SUREFIRE_SKIP="-Dsurefire.skip.ut=true"
- PROFILE=integrationTesting FIXTURES="-Dns-fixtures=DOCUMENT_MK,DOCUMENT_NS,DOCUMENT_JDBC"
  SUREFIRE_SKIP="-Dsurefire.skip.ut=true"
script: mvn verify -P${PROFILE} ${FIXTURES} ${SUREFIRE_SKIP}
language: java
jdk:
- oraclejdk7
before_install:
- sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 7F0CEB10
- echo 'deb http://downloads-distro.mongodb.org/repo/ubuntu-upstart dist 10gen' |
  sudo tee /etc/apt/sources.list.d/mongodb.list
- sudo apt-get update
- sudo apt-get install mongodb-org=2.6.1 mongodb-org-server=2.6.1 mongodb-org-shell=2.6.1
  mongodb-org-mongos=2.6.1 mongodb-org-tools=2.6.1
